services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    
    # 【環境變數設】
    environment:
      POSTGRES_PASSWORD: pi_pass
      POSTGRES_DB: pi_database
      POSTGRES_USER: pi

    # 【資料持久化】
    #volumes:
    #  - ./data:/var/lib/postgresql/data

    # 【網路連接埠】
    ports:
      - "5432:5432"

    # 啟用健康檢查 (可選，但推薦)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      